#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed

if [ -z "$1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c5 "$1"
fi
