#!/usr/bin/env bash
# gives info about a file
FILE=school;
if test -e "$FILE"; then
        echo "$FILE file exists";
        if test -s "$FILE"; then
                echo "$FILE file is not empty";
    else
                echo "$FILE file is empty";
    fi;
        if test -f "$FILE"; then
                echo "$FILE file is a regular file";
        fi;
else
        echo "$FILE file does not exist";
fi
