#!/usr/bin/env bash
# localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.*$/127.0.0.2 localhost/' ~/hosts.new
if grep -vq "8.8.8.8 facebook.com" ~/hosts.new
then
	echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts